In [1]:
# Importing Libraries
import hashlib as hashlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
# import Crypto.Cipher
# from Crypto.Cipher import XOR
import base64
warnings.filterwarnings("ignore")

In [2]:
# Importing dataset - capturing file handling errors. 
try:
    bankset = pd.read_csv(open('bank.csv', 'rb'))
    banksetcopy = bankset.copy()

except:
    print("Error Loading file(s),  current working directory:", format(os.getcwd()))

In [3]:
banksetbaseline = bankset.copy()

In [4]:
bankset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# bankset.info()

In [6]:
# List of Columns that need masking
# User / Account / Parties / Instruments / Trades

In [7]:
s='hello, world'
# mask = 'x' 
def mask_to_len(s,m):
    mstr=m
    for i in s:     
        mstr = mstr+ str("m")
    return mstr
m = mask_to_len(s,"")

In [8]:
def data_masking(s,m):
    m = mask_to_len(s,m)
    s=''.join(chr(ord(a)^ord(b)) for a,b in zip(s,m))
    data =s
    new = data.encode('UTF-16')
#     data = print(new.decode('UTF-16'))
    data = new.decode('UTF-16')
    return data

In [9]:
source_df= bankset.copy()
source_df.drop(['RowNumber', 'CustomerId', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'], axis=1, inplace=True, errors='ignore')

In [10]:
source_df

        Surname
0      Hargrave
1          Hill
2          Onio
3          Boni
4      Mitchell
...         ...
9995   Obijiaku
9996  Johnstone
9997        Liu
9998  Sabbatini
9999     Walker

[10000 rows x 1 columns]

In [11]:
source_df.drop(['Masked_Column','ReIdentified_Column'], axis=1, inplace=True, errors='ignore')

In [12]:
source_df['Masked_Column'] = source_df['Surname'].apply(lambda x: data_masking(x,"m"))

In [13]:
source_df['ReIdentified_Column'] = source_df['Masked_Column'].apply(lambda x: data_masking(x,"m"))

In [14]:
source_df

        Surname Masked_Column ReIdentified_Column
0      Hargrave     %
\n
            Hargrave
1          Hill          %                Hill
2          Onio          "                Onio
3          Boni          /                Boni
4      Mitchell                   Mitchell
...         ...           ...                 ...
9995   Obijiaku      "
            Obijiaku
9996  Johnstone     '
           Johnstone
9997        Liu           !                 Liu
9998  Sabbatini     >

           Sabbatini
9999     Walker        :
              Walker

[10000 rows x 3 columns]

In [15]:
source_df.to_csv("masked_data.csv")

In [16]:
dest_df= bankset.copy()
dest_df.drop(['RowNumber', 'CustomerId', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'], axis=1, inplace=True, errors='ignore')

In [17]:
dest_df

        Surname
0      Hargrave
1          Hill
2          Onio
3          Boni
4      Mitchell
...         ...
9995   Obijiaku
9996  Johnstone
9997        Liu
9998  Sabbatini
9999     Walker

[10000 rows x 1 columns]

In [18]:
dest_df.drop(['Masked_Column','ReIdentified_Column'], axis=1, inplace=True, errors='ignore')

In [19]:
dest_df['Surname'] = source_df['Surname'].apply(lambda x: data_masking(x,"m"))

In [20]:
dest_df

        Surname
0     %
\n

1          %
2          "
3          /
4       
...         ...
9995   "

9996  '

9997        !
9998  >


9999     :


[10000 rows x 1 columns]

In [21]:
dest_df['Surname'] = dest_df['Surname'].apply(lambda x: data_masking(x,"m"))

In [22]:
dest_df

        Surname
0      Hargrave
1          Hill
2          Onio
3          Boni
4      Mitchell
...         ...
9995   Obijiaku
9996  Johnstone
9997        Liu
9998  Sabbatini
9999     Walker

[10000 rows x 1 columns]

In [ ]:
source_df= bankset.head()
source_df.drop(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'], axis=1, inplace=True, errors='ignore')

In [ ]:
source_df.columns

In [ ]:
def hash(sourcedf,destinationdf,*column):
    columnName = 'hash_'
    for i in column:
        columnName = columnName + i
    hashColumn = pd.Series()
    for i in range((len(sourcedf[column[0]]))):
        concatstr = ''
        for j in column:
            concatstr = concatstr + sourcedf[j][i]
        hashColumn.at[i] = hashlib.sha512( concatstr.encode("utf-8") ).hexdigest()
    destinationdf[columnName] = hashColumn

In [ ]:
dest_hash = source_df.copy()

In [ ]:
source_df

In [ ]:
hash(source_df,dest_hash,'Surname')

In [ ]:
# bankset.head()

In [ ]:
dest_hash.head()

In [ ]:
# from Crypto.Cipher import XOR
# import base64

In [ ]:
import base64
def encode(key, clear):
    enc = []
    for i in range(len(clear)):
        key_c = key[i % len(key)]
        enc_c = chr((ord(clear[i]) + ord(key_c)) % 256)
        enc.append(enc_c)
    return base64.urlsafe_b64encode("".join(enc).encode()).decode()

def decode(key, enc):
    dec = []
    enc = base64.urlsafe_b64decode(enc).decode()
    for i in range(len(enc)):
        key_c = key[i % len(key)]
        dec_c = chr((256 + ord(enc[i]) - ord(key_c)) % 256)
        dec.append(dec_c)
    return "".join(dec)

In [ ]:
source_df['Masked_Column'] = source_df['Surname'].apply(lambda x: encode('password',x))

In [ ]:
source_df

In [ ]:
source_df['ReIdentified_Column'] = source_df['Masked_Column'].apply(lambda x: decode('password', x))

In [ ]:
source_df

In [ ]:
INT_BITS = 64
def leftShift(n,d):
    return (n << d)|(n >> (INT_BITS - d))

In [ ]:
print(leftShift(123, 2))

In [ ]:
def rightShift(n, d):

	# In n>>d, first d bits are 0.
	# To put last 3 bits of at
	# first, do bitwise or of n>>d
	# with n <<(INT_BITS - d)
	return (n >> d)|(n << (INT_BITS - d)) & 0xFFFFFFFF

In [ ]:
print(rightShift(492, 2))

In [ ]:
source_df

In [ ]:
# def stringRotate (n,d):

In [ ]:
# Function to rotate string left and right by d length

def stringRightRotate(input,d):

# slice string in two parts for left and right
    Lfirst = input[0 : d]
    Lsecond = input[d :]
    Rfirst = input[0 : len(input)-d]
    Rsecond = input[len(input)-d : ]

    # now concatenate two parts together
#     print ("Left Rotation : ", (Lsecond + 'XX' + Lfirst))
    print ("Right Rotation : ", (Rsecond + Rfirst))
    return (Rsecond +Rfirst)

# # Driver program
# if __name__ == "__main__":
#     input = 'GeeksforGeeks'
#     d=2
#     stringRotate(input,d)

In [ ]:
# Function to rotate string left and right by d length

def stringLeftRotate(input,d):

# slice string in two parts for left and right
    Lfirst = input[0 : d]
    Lsecond = input[d :]
    Rfirst = input[0 : len(input)-d]
    Rsecond = input[len(input)-d : ]

    # now concatenate two parts together
    print ("Left Rotation : ", (Lsecond + Lfirst))
#     print ("Right Rotation : ", (Rsecond + Rfirst))
    return (Lsecond + Lfirst)

# Driver program
if __name__ == "__main__":
    input = 'ClearText'
    d=2
    stringRotate(input,d)

In [ ]:
rotated_text = stringLeftRotate(input,2)

In [ ]:
stringRightRotate(rotated_text,2)

In [ ]:
source_df['Masked_Column'] = source_df['Surname'].apply(lambda x: stringRotate(x,2))

In [ ]:
source_df

In [ ]:
source_df['Masked_Column'] = source_df['Surname'].apply(lambda x: encode('password',x))

In [ ]:
source_df

In [ ]:
# Python3 code to
# rotate bits of number

INT_BITS = 32

# Function to left
# rotate n by d bits
def leftRotate(n, d):

	# In n<<d, last d bits are 0.
	# To put first 3 bits of n at
	# last, do bitwise or of n<<d
	# with n >>(INT_BITS - d)
	return (n << d)|(n >> (INT_BITS - d))

# Function to right
# rotate n by d bits
def rightRotate(n, d):

	# In n>>d, first d bits are 0.
	# To put last 3 bits of at
	# first, do bitwise or of n>>d
	# with n <<(INT_BITS - d)
	return (n >> d)|(n << (INT_BITS - d)) & 0xFFFFFFFF

# Driver program to
# test above functions
n = 16
d = 2

print("Left Rotation of",n,"by"
	,d,"is",end=" ")
print(leftRotate(n, d))

print("Right Rotation of",n,"by"
	,d,"is",end=" ")
print(rightRotate(n, d))

# This code is contributed by
# Smitha Dinesh Semwal

In [ ]:
len(s)

In [ ]:
s='hello, world'
# mask = 'x' 
def mask_to_len(s,m):
    mstr=m
    for i in s:
#         mstr= mstr + str(ord(m)^ord(i))
#         print("i", (i))
        
        mstr = mstr+ str("m")
#     print("mstr", mstr)
    return mstr
m = mask_to_len(s,"")
# m

In [ ]:
def data_masking(s,m):
#     print(s,m)
    m = mask_to_len(s,m)
#     print("m", m)
    s=''.join(chr(ord(a)^ord(b)) for a,b in zip(s,m))
    data =s
    new = data.encode('UTF-16')
#     data = print(new.decode('UTF-16'))
    data = new.decode('UTF-16')
    return data

In [ ]:
dm = data_masking('\x03\x08\x1aM\x1a\x02\x1f\x01\t',"m")
# dm

In [ ]:
s='hello, world'

In [ ]:
m

In [ ]:
s=''.join(chr(ord(a)^ord(b)) for a,b in zip(s,m))
s

In [ ]:
source_df

In [ ]:
source_df.drop(['Masked_Column','ReIdentified_Column'], axis=1, inplace=True, errors='ignore')

In [ ]:
source_df['Masked_Column'] = source_df['Surname'].apply(lambda x: data_masking(x,"m"))

In [ ]:
source_df['ReIdentified_Column'] = source_df['Masked_Column'].apply(lambda x: data_masking(x,"m"))

In [ ]:
source_df

In [ ]:
source_df.to_csv("masked_data.csv")

In [ ]:
s=''.join(chr(ord(a)^ord(b)) for a,b in zip(s,m))
s

In [ ]:
data =s
new = data.encode('UTF-16')
print(new.decode('UTF-16'))

In [ ]:
# data = u'£21'
app = data.encode('UTF-8')
print(app.decode())

new = data.encode('UTF-16')
print(new.decode('UTF-16'))

In [ ]:
mask_to_len(s,"")

In [ ]:
>>> s=''.join(chr(ord(a)^ord(b)) for a,b in zip(s,m))
>>> s

In [ ]:
>>> s='hello, world'
>>> m='markmarkmark'
>>> s=''.join(chr(ord(a)^ord(b)) for a,b in zip(s,m))
>>> s

In [ ]:
s=''.join(chr(ord(a)^ord(b)) for a,b in zip(s,m))
s

In [ ]:
s